//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.AMISDemo.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource_VN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_VN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.AMISDemo.Core.Resource.Resource_VN", typeof(Resource_VN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Tài Khoản.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập.
        /// </summary>
        public static string Authorize {
            get {
                return ResourceManager.GetString("Authorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Ngân Hàng.
        /// </summary>
        public static string BankName {
            get {
                return ResourceManager.GetString("BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository bị null.
        /// </summary>
        public static string CheckRepository {
            get {
                return ResourceManager.GetString("CheckRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Code đã được tạo.
        /// </summary>
        public static string CodeCreated {
            get {
                return ResourceManager.GetString("CodeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhóm khách hàng đã được tạo.
        /// </summary>
        public static string CustomerGroup_Name {
            get {
                return ResourceManager.GetString("CustomerGroup_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị đã được tạo.
        /// </summary>
        public static string Department_Name {
            get {
                return ResourceManager.GetString("Department_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Đơn Vị.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT Authorization header using  your token in the text input below \n\n&quot; +
        ///        &quot;Example: \&quot;Bearer 1234asdfa\&quot;.
        /// </summary>
        public static string DescriptionAuthorize {
            get {
                return ResourceManager.GetString("DescriptionAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Sinh.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không được trống.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Nhân Viên đã được tạo.
        /// </summary>
        public static string EmployeeCode {
            get {
                return ResourceManager.GetString("EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Nhân Viên.
        /// </summary>
        public static string EmployeeCodeVN {
            get {
                return ResourceManager.GetString("EmployeeCodeVN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Import không được rỗng.
        /// </summary>
        public static string EmptyFile {
            get {
                return ResourceManager.GetString("EmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        public static string ExcelNameEmployee {
            get {
                return ResourceManager.GetString("ExcelNameEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy người dùng.
        /// </summary>
        public static string FindAccount {
            get {
                return ResourceManager.GetString("FindAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đơn vị.
        /// </summary>
        public static string FindDepartment {
            get {
                return ResourceManager.GetString("FindDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy đối tượng .
        /// </summary>
        public static string FindObject {
            get {
                return ResourceManager.GetString("FindObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy vị trí.
        /// </summary>
        public static string FindPosition {
            get {
                return ResourceManager.GetString("FindPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã refresh token không tồn tại.
        /// </summary>
        public static string FindRefreshToken {
            get {
                return ResourceManager.GetString("FindRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File được tải phải định dạng .xlxs.
        /// </summary>
        public static string FormatFileExcel {
            get {
                return ResourceManager.GetString("FormatFileExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Nhân Viên.
        /// </summary>
        public static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới Tính.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trùng số tài khoản với nhân viên khác trong hệ thống .
        /// </summary>
        public static string IDCard {
            get {
                return ResourceManager.GetString("IDCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id để import không được null.
        /// </summary>
        public static string IdImport {
            get {
                return ResourceManager.GetString("IdImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp Lệ.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string OrdinalNumber {
            get {
                return ResourceManager.GetString("OrdinalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không được để trống.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên vị trí đã được tạo.
        /// </summary>
        public static string Position_Name {
            get {
                return ResourceManager.GetString("Position_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Vị trí.
        /// </summary>
        public static string PositionName {
            get {
                return ResourceManager.GetString("PositionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh token đã hết hạn.
        /// </summary>
        public static string RefreshTokenExpire {
            get {
                return ResourceManager.GetString("RefreshTokenExpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đăng nhập hoặc mật khẩu không đúng.
        /// </summary>
        public static string SingInFail {
            get {
                return ResourceManager.GetString("SingInFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH SÁCH NHÂN VIÊN.
        /// </summary>
        public static string titleExcel {
            get {
                return ResourceManager.GetString("titleExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token không hợp lệ.
        /// </summary>
        public static string TokenInvalid {
            get {
                return ResourceManager.GetString("TokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tương ứng thông tin access token trong refresh token.
        /// </summary>
        public static string TokenMatch {
            get {
                return ResourceManager.GetString("TokenMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi nhập từ người dùng.
        /// </summary>
        public static string UsgMessage {
            get {
                return ResourceManager.GetString("UsgMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID không tìm thấy.
        /// </summary>
        public static string ValidateId {
            get {
                return ResourceManager.GetString("ValidateId", resourceCulture);
            }
        }
    }
}
